version: '3.8'

services:
  api:
    image: ninepiece2/traffic-control-system:latest
    container_name: Traffic-Control-System
    ports:
      - "8443:8443"
    volumes:
      - /root/certs:/https:ro
    environment:
      - ASPNETCORE_URLS=https://*:8443;http://*:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ssl.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/ssl.key
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - SyncfusionLicense=${SyncfusionLicense}
    command: ["dotnet", "Traffic-Control-System.dll"]
    restart: always