services:
  client:
    image: ninepiece2/traffic-control-system:client
    container_name: Smart-Traffic-Control-System-Client
    privileged: true  # Needed to allow access to GPIO and camera devices
    devices:
      - "/dev/gpiomem:/dev/gpiomem"  # GPIO access
      - "/dev/video0:/dev/video0"    # Camera access
    volumes:
      - ./config:/app/SmartTrafficControlSystemClient/ConfigFile
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
