name: Client CI/CD Pipeline

on:
  push:
    branches:
      - master
    paths:
      - RaspPiPythonScripts/**
  workflow_dispatch:

jobs:
  Build-Client:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and use unique Docker context
        run: |
          docker context create context-${{ github.run_id }}-${{ github.job }} || true
          docker context use context-${{ github.run_id }}-${{ github.job }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: context-${{ github.run_id }}-${{ github.job }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          context: ./RaspPiPythonScripts
          file: ./RaspPiPythonScripts/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/traffic-control-system:client

      - name: Remove unused Docker images
        run: docker image prune -af
