name: Client CI/CD Pipeline

on:
  push:
    branches:
      - master
    paths:
      - RaspPiPythonScripts/**

jobs:
    Build-Client:
        runs-on: self-hosted
        steps:
        - name: Checkout
          uses: actions/checkout@v4
    
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
    
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
    
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            platforms: linux/arm64
            context: ./RaspPiPythonScripts
            file: ./RaspPiPythonScripts/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/traffic-control-system:client

        - name: Remove unused Docker images
          run: docker image prune -af